[features]
seeds = false
skip-lint = false

[programs.localnet]
eclipx_core = "Ec1pXmjiR5DVFhbYr4urnUdFKNhKwgjJXwbkFCfCa5sM"

[programs.devnet]
eclipx_core = "Ec1pXmjiR5DVFhbYr4urnUdFKNhKwgjJXwbkFCfCa5sM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# touch: e5c22b7b

# touch: b54eb7b5

# touch: 4d579286

# touch: 326d255f

# touch: f55869cb

# touch: 330c65ad

# touch: 0c3c562d
