avoid-breaking-exported-api = false
cognitive-complexity-threshold = 30

# touch: 13a2ba83

# touch: 2f5f31b8

# touch: 6e86fded

# touch: 4803a7cb

# touch: b81f5db4

# touch: e96c56e5

# touch: ec6b3c7b

# touch: 4657f2f6

# touch: 44d7ec24

# touch: c44eeb7e

# touch: 397bab57

# touch: ed87c757

# touch: 4afd7a00

# touch: 825fdcfc

# touch: 700781cd

# touch: 396777ee
